import type { ReasoningMechanism } from "./types.ts";

/**
 * The 21-mechanism registry — canonical copy. Mirrored verbatim into
 * supabase/functions/_shared/reasoning/mechanisms.ts; scripts/check-domain-drift.mjs
 * fails the build if the two ever diverge.
 *
 * relevantPerformanceSignals is empty on most entries BY DESIGN. Every
 * mechanism here was checked against all 14 signals functions/api/_scan.ts
 * actually measures; only 3 mappings survive real scrutiny (Social Proof,
 * Authority Signaling). Tempting-but-rejected pairings, for the record —
 * not encoded in data because they didn't survive scrutiny, documented here
 * so the next person doesn't re-propose them without re-examining why they
 * were cut:
 *   - LCP/TBT ↔ Cognitive Load Theory: rejected. CLT concerns working-memory
 *     load from information density/complexity, not page-load latency —
 *     a real but different construct. No signal here measures information
 *     density.
 *   - CLS ↔ any of the 21: rejected. buildScaffoldEvidence() already cites
 *     CLS as trust-relevant on its own terms; nothing in this registry
 *     names a mechanism specifically about visual-stability-driven trust
 *     collapse, so forcing a link would be assigning it to the nearest
 *     available label rather than the correct one.
 *   - pricing_link presence ↔ Anchoring: rejected. Presence of a pricing
 *     link says nothing about how prices are structured or anchored once
 *     found — a presence/absence signal can't support a claim about
 *     numerical framing.
 */
export const MECHANISMS: ReasoningMechanism[] = [
  // ── Family 01 — Cognitive Load & Information Processing ──────────────────
  {
    id: "cognitive-load-theory", name: "Cognitive Load Theory", familyId: "cognitive-load",
    definition: "Working memory has limited capacity, and interface design that exceeds it degrades comprehension regardless of the information's intrinsic value.",
    underlyingMechanism: "Working memory holds only a small number of active chunks. Three load types compete for it: intrinsic (the task's real complexity), extraneous (imposed by poor presentation), germane (effort building real understanding). The only lever a page controls is extraneous load.",
    evidenceStrength: "strong",
    evidenceNotes: "Sweller's theory (1988 onward) is among the most replicated frameworks in educational psychology. Its extension to web/UX design is a reasonable but less formally tested extrapolation — the underlying working-memory constraint (Baddeley's model) is not in serious dispute.",
    epistemicWarnings: [],
    manifestation: "A pricing page listing fourteen feature bullets per tier with no visual grouping, forcing the visitor to hold all fourteen in mind simultaneously.",
    diagnosticQuestions: ["Is the visitor's difficulty about not understanding the offer — or about how much they must hold in mind at once to evaluate it?"],
    misinterpretations: "Not every confusing page is a load problem — a simple page can still fail on trust or motivation grounds. Overuse shows up as stripping decision-relevant information in the name of \"simplicity,\" trading a load problem for a value-uncertainty problem.",
    relevantFrictionMechanisms: [{ id: "cognitive_load", primary: true }, { id: "ordering_error", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["A page can be low-load and still fail on trust, motivation, or value clarity — load theory says nothing about those."],
    references: [{ label: "Sweller, 1988 onward", note: "Cognitive Load Theory" }, { label: "Baddeley", note: "working-memory model" }],
  },
  {
    id: "hicks-law", name: "Hick's Law", familyId: "cognitive-load",
    definition: "Decision time increases logarithmically with the number and complexity of available choices.",
    underlyingMechanism: "Each additional option must be encoded, compared against alternatives already held in mind, and folded into a running best-choice estimate — a serial cognitive process.",
    evidenceStrength: "contextual",
    evidenceNotes: "Strong within its original domain (Hick 1952, Hyman 1953) for simple, well-defined tasks. Weaker extrapolated to complex purchase decisions — real buying involves motivation and risk evaluation a reaction-time task doesn't capture, so it describes decision latency, not decision quality.",
    epistemicWarnings: ["Describes latency, not quality — do not cite as evidence a decision was WRONG, only that it was slow."],
    manifestation: "A plan selector with nine undifferentiated tiers, where visitors visibly hesitate or abandon before evaluating any single option in depth.",
    diagnosticQuestions: ["If this decision is taking longer than it should, is that because the options are genuinely hard to compare — or because there are just more of them than the decision warrants?"],
    misinterpretations: "Frequently conflated with choice overload, a motivational effect, when Hick's Law is strictly about processing time. Don't invoke it to argue for fewer options when the real problem is poor differentiation between the options that already exist.",
    relevantFrictionMechanisms: [{ id: "cognitive_load", primary: true }, { id: "commitment_anxiety", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Not a justification for reducing option count when the real issue is that existing options are poorly differentiated, not too numerous."],
    references: [{ label: "Hick, 1952" }, { label: "Hyman, 1953" }],
  },
  {
    id: "recognition-over-recall", name: "Recognition Over Recall", familyId: "cognitive-load",
    definition: "People decide more accurately and effortlessly when relevant information is visible in context than when they must retrieve it from memory.",
    underlyingMechanism: "Recognition is a cued memory process — the environment supplies the retrieval cue. Recall requires unaided, effortful search with no external cue, a categorically harder operation.",
    evidenceStrength: "strong",
    evidenceNotes: "One of Nielsen's ten usability heuristics (1994), grounded in decades of recognition-vs-recall research (Mandler, Tulving). Application to any specific interface decision is more heuristic than case-by-case isolated, but the underlying memory asymmetry is not disputed.",
    epistemicWarnings: [],
    manifestation: "A checkout flow that shows cart contents and running total only on a separate page, forcing the buyer to recall what they selected.",
    diagnosticQuestions: ["At the exact moment this person needs to decide, is the information they need actually visible — or are they relying on memory from three steps ago?"],
    misinterpretations: "Not a mandate to show everything at once — that reintroduces load. The principle is placing the specific decision-relevant information near the decision point, not maximizing on-screen information generally.",
    relevantFrictionMechanisms: [{ id: "cognitive_load", primary: true }, { id: "trust_deficit", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Redundantly re-displaying information the user has already confidently used is clutter, not an application of this principle."],
    references: [{ label: "Nielsen, 1994", note: "usability heuristics" }, { label: "Mandler; Tulving", note: "recognition vs. recall memory research" }],
  },

  // ── Family 02 — Trust, Credibility & Authority ────────────────────────────
  {
    id: "social-proof", name: "Social Proof", familyId: "trust-credibility",
    definition: "People treat the observed behavior of similar others as evidence of the correct choice, especially under uncertainty.",
    underlyingMechanism: "Evaluating a choice directly is effortful under ambiguity, so the mind substitutes an easier question — \"what are people like me doing?\" Most powerful when the observer feels similar to those observed.",
    evidenceStrength: "contextual",
    evidenceNotes: "Cialdini's formulation (1984) rests on real grounding (Asch, Sherif), but effect size depends heavily on similarity and specificity of the proof. Well-established in low-stakes consumer contexts; considerably weaker — sometimes reversed — in high-stakes B2B purchasing.",
    epistemicWarnings: [],
    manifestation: "A logo wall of unnamed \"trusted by 500+ companies\" with no company the visitor recognizes and no indication of size or industry similarity to their own.",
    diagnosticQuestions: ["Is this proof actually similar enough to this specific visitor to function as evidence — or is it just occupying the space where trust evidence usually goes?"],
    misinterpretations: "Vague, generic proof is not the same intervention as specific, similar-peer proof. Overused when it substitutes for a buyer's own evaluation criteria in complex B2B purchases, where peer behavior is a weak signal relative to fit.",
    relevantFrictionMechanisms: [{ id: "trust_deficit", primary: true }, { id: "identity_friction", primary: false }],
    relevantPerformanceSignals: [
      { signal: "third_party_review_link", status: "proposed", rationale: "buildScaffoldEvidence() already cites this exact signal as social-proof evidence (\"NN/g: users trust testimonials on external sites more than the same claim made on-site\") — the mapping is a direct restatement of the scan engine's own documented rationale, not a new inference." },
      { signal: "on_site_testimonial", status: "proposed", rationale: "Same source citation, the weaker (on-site) form of the same signal — buildScaffoldEvidence() explicitly weights it lower than the third-party form for exactly this reason." },
    ],
    contraindications: ["Not interchangeable with generic, unspecific proof — a visitor evaluating fit needs specific, similar-peer evidence, not aggregate counts."],
    references: [{ label: "Cialdini, 1984" }, { label: "Asch" }, { label: "Sherif" }],
  },
  {
    id: "authority-signaling", name: "Authority & Expertise Signaling", familyId: "trust-credibility",
    definition: "People assign more credibility to claims associated with recognized expertise, independent of the claim's own merits.",
    underlyingMechanism: "Verifying a claim's substance is costly, so the mind uses source credibility as a proxy for validity — cognitive delegation, a heuristic, not a validity check.",
    evidenceStrength: "mixed",
    evidenceNotes: "Deference to authority is well documented (Milgram, though transfer to marketing is inferential). In digital B2B specifically, evidence is thinner — badges help, hurt, or do nothing depending on category familiarity, with real backfire risk when a signal feels irrelevant.",
    epistemicWarnings: ["Real backfire risk when the signal feels manufactured or irrelevant to the specific doubt present — this is not a strictly positive-EV tactic."],
    manifestation: "A security/compliance badge near a checkout CTA when the buyer's live hesitation is actually about pricing, not data security.",
    diagnosticQuestions: ["Does this specific authority signal address the specific doubt this visitor has right now — or is it a generic credibility marker parked in a high-visibility spot?"],
    misinterpretations: "Not interchangeable with relevance — an impressive but irrelevant credential doesn't resolve doubt and can raise suspicion. Most effective against competence/legitimacy doubt; ineffective against price, fit, or timing doubt.",
    relevantFrictionMechanisms: [{ id: "trust_deficit", primary: true }, { id: "value_uncertainty", primary: false }],
    relevantPerformanceSignals: [
      { signal: "security_badges", status: "proposed", rationale: "buildScaffoldEvidence() already cites this exact signal as an authority/legitimacy marker (\"Baymard Institute B2B research: compliance certifications matter more than consumer trust badges for this buyer\") — direct restatement of documented scan-engine rationale." },
    ],
    contraindications: ["Do not apply as a default trust-building tactic without first diagnosing which specific trust gap is present."],
    references: [{ label: "Milgram" }, { label: "Cialdini, 1984" }],
  },
  {
    id: "halo-effect", name: "Halo Effect", familyId: "trust-credibility",
    definition: "A single positive impression about an entity biases evaluation of its unrelated qualities.",
    underlyingMechanism: "Global evaluative judgments are cheaper to form than attribute-by-attribute analysis. Once an impression forms, unrelated attributes get colored to stay consistent with it.",
    evidenceStrength: "strong",
    evidenceNotes: "One of the most robustly replicated findings in person perception since Thorndike (1920). Directionally strong; precise effect size in any given digital-product context varies substantially by study and category.",
    epistemicWarnings: [],
    manifestation: "A visually polished pricing page causing visitors to assume equally polished product/support quality, with no actual product evidence present.",
    diagnosticQuestions: ["Is this positive first impression backed by evidence for the specific thing the visitor needs to trust — or is it borrowing credibility from an unrelated impression?"],
    misinterpretations: "Not a justification for polishing surface aesthetics as a substitute for a real evidence gap — a halo that fails to survive contact with the actual product converts a trust problem into a churn problem downstream.",
    relevantFrictionMechanisms: [{ id: "trust_deficit", primary: true }, { id: "value_uncertainty", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Strongest only at first exposure — weakens fast once the visitor has real product evidence, so it cannot substitute for that evidence long-term."],
    references: [{ label: "Thorndike, 1920" }, { label: "Nisbett & Wilson" }],
  },

  // ── Family 03 — Risk Perception & Loss Aversion ───────────────────────────
  {
    id: "loss-aversion", name: "Loss Aversion", familyId: "risk-loss-aversion",
    definition: "Losses are experienced as more psychologically significant than equivalent gains.",
    underlyingMechanism: "Value is computed relative to a reference point, and the value function is steeper for losses than gains around that point.",
    evidenceStrength: "strong",
    evidenceNotes: "A foundational, extensively replicated result of Prospect Theory (Kahneman & Tversky, 1979). The commonly cited \"losses loom twice as large\" ratio is an approximation from specific experiments, not a universal constant.",
    epistemicWarnings: ["The \"2x\" ratio is not a transferable constant — do not cite a specific multiplier as if it generalizes."],
    manifestation: "Framing a cancellation flow around what the customer will lose produces stronger retention than framing an equivalent upgrade around the same gains.",
    diagnosticQuestions: ["Is this decision currently framed as a gain to get or a loss to avoid — and does that framing match how the trade-off actually works?"],
    misinterpretations: "Not a license for manufactured scarcity or fear-based urgency — those are separate, often manipulative tactics. The effect concerns psychological framing of an identical outcome, not actual risk.",
    relevantFrictionMechanisms: [{ id: "commitment_anxiety", primary: true }, { id: "value_uncertainty", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Conflating psychological framing with actual risk produces dishonest copy — the trade-off's real magnitude must not change, only its framing."],
    references: [{ label: "Kahneman & Tversky, 1979", note: "Prospect Theory" }],
  },
  {
    id: "status-quo-bias", name: "Status Quo Bias", familyId: "risk-loss-aversion",
    definition: "People disproportionately prefer the current state of affairs, treating it as the reasonable baseline.",
    underlyingMechanism: "Changing the status quo requires an active decision and creates possibility of attributable regret; maintaining it requires no decision at all.",
    evidenceStrength: "contextual",
    evidenceNotes: "Well-established in default-effect research (opt-in/opt-out organ donation), but magnitude is highly sensitive to how much active effort switching requires — large when switching costs are high, nearly absent when trivial.",
    epistemicWarnings: [],
    manifestation: "A visitor already using a competitor hesitates to switch not because your product is worse, but because switching carries perceived setup effort that staying does not.",
    diagnosticQuestions: ["Is this hesitation about the merits of my offer — or about the mere fact that switching requires an active decision that staying doesn't?"],
    misinterpretations: "Easily conflated with genuine product-fit rejection — real switching costs (data migration, retraining) aren't a bias at all. Only label it bias when switching cost is genuinely smaller than the visitor's behavior implies.",
    relevantFrictionMechanisms: [{ id: "commitment_anxiety", primary: true }, { id: "ordering_error", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Not meaningful for genuinely novel-category first purchases — there is no status quo to anchor to."],
    references: [{ label: "Samuelson & Zeckhauser" }],
  },
  {
    id: "endowment-effect", name: "Endowment Effect", familyId: "risk-loss-aversion",
    definition: "People assign more value to something once they perceive it as their own than they did beforehand.",
    underlyingMechanism: "Ownership shifts the reference point for loss-aversion calculations — giving something up registers as a loss rather than forgoing a gain, even absent real ownership transfer.",
    evidenceStrength: "mixed",
    evidenceNotes: "The original mug experiments (Kahneman, Knetsch & Thaler, 1990) are famous, but this is one of the more genuinely contested findings of the replication era — later studies found substantially smaller, more conditional effects. Treat it as real but reliably smaller than its popular reputation.",
    epistemicWarnings: ["Reliably smaller and more conditional in post-2010 replications than the 1990 original suggested — do not cite the original effect size as current consensus."],
    manifestation: "Trial users who've configured a workspace or imported data show churn reluctance not explained by satisfaction alone.",
    diagnosticQuestions: ["Has this visitor actually built or invested something they'd feel they're giving up — or does the funnel just assume an endowment effect that was never created?"],
    misinterpretations: "Frequently overclaimed to justify \"let them try it and they won't want to give it up\" trial design — the effect needs genuine investment or personalization to exist at all.",
    relevantFrictionMechanisms: [{ id: "commitment_anxiety", primary: true }, { id: "identity_friction", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Passive trial exposure with no setup or personalization creates little to no endowment effect regardless of duration."],
    references: [{ label: "Kahneman, Knetsch & Thaler, 1990" }],
  },

  // ── Family 04 — Choice Architecture & Decision Complexity ─────────────────
  {
    id: "default-effect", name: "Default Effect", familyId: "choice-architecture",
    definition: "People disproportionately select whatever option is pre-set as the default.",
    underlyingMechanism: "A default reads as an implicit recommendation from the choice architect, combined with the effort cost of actively overriding it.",
    evidenceStrength: "strong",
    evidenceNotes: "Among the most robust findings in applied behavioral economics — retirement auto-enrollment (Madrian & Shea, 2001) and cross-country organ-donation comparisons show large, consistent effects.",
    epistemicWarnings: [],
    manifestation: "A pricing page pre-selecting annual billing shifts a meaningful share of purchases to annual commitment with no persuasive copy at all.",
    diagnosticQuestions: ["What is currently defaulted here, and is that default the option that serves this visitor's interest — or the business's preference?"],
    misinterpretations: "Using defaults to steer users toward options that don't serve their interest — pre-checked add-ons, defaulted high-commitment tiers — crosses from choice architecture into a trust-damaging dark pattern.",
    relevantFrictionMechanisms: [{ id: "ordering_error", primary: true }, { id: "commitment_anxiety", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["A default that serves the seller at the buyer's expense is a dark pattern, not a legitimate application of this mechanism — the distinction is intent and benefit, not the mechanism itself."],
    references: [{ label: "Madrian & Shea, 2001" }, { label: "Johnson & Goldstein" }],
  },
  {
    id: "decoy-effect", name: "Decoy Effect (Asymmetric Dominance)", familyId: "choice-architecture",
    definition: "A third option, clearly inferior to one existing option but not the other, shifts preference toward the option it's dominated by.",
    underlyingMechanism: "Absolute evaluation is hard, so people rely on relative comparison. A decoy gives an easy, confident comparison that lends unwarranted confidence to the whole judgment.",
    evidenceStrength: "mixed",
    evidenceNotes: "Strong in controlled settings (Huber, Payne & Puto, 1982). Thinner for durable B2B purchases over long cycles, where buyers build independent comparisons — the effect can be neutralized entirely by informed research.",
    epistemicWarnings: [],
    manifestation: "A three-tier pricing page where the middle tier looks \"obvious\" relative to a bottom tier stripped of features.",
    diagnosticQuestions: ["Is the middle option winning because it's genuinely the best fit — or because the other two tiers were shaped to make it look that way?"],
    misinterpretations: "Effective for a first glance; unreliable once a buyer starts independent evaluation. Works on relative comparison within your own tiers; does nothing against external competitor comparison.",
    relevantFrictionMechanisms: [{ id: "ordering_error", primary: true }, { id: "value_uncertainty", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Neutralized entirely by an informed buyer doing independent comparison — do not rely on it as a durable substitute for genuine tier differentiation."],
    references: [{ label: "Huber, Payne & Puto, 1982" }],
  },
  {
    id: "choice-overload", name: "Choice Overload", familyId: "choice-architecture",
    definition: "Beyond a certain point, more options can reduce rather than increase the likelihood of choosing.",
    underlyingMechanism: "Each additional option imposes comparison cost and anticipated-regret cost; past a threshold these outweigh the benefit of a better potential match.",
    evidenceStrength: "weak",
    evidenceNotes: "The single most important honesty flag in this document. The jam-study origin (Iyengar & Lepper, 2000) is famous, but the large meta-analysis (Scheibehenne et al., 2010) found the average effect close to zero, heavily moderated by category familiarity and differentiation.",
    epistemicWarnings: [
      "Average effect across replications is close to zero (Scheibehenne, Greifeneder & Todd, 2010) — do not present the original 2000 jam-study result as representative of the current evidence base.",
      "Only diagnose choice overload when option count is high AND options are hard to differentiate AND the buyer lacks strong pre-existing preferences — dropping any one condition weakens or eliminates the effect.",
    ],
    manifestation: "A features/add-ons page with twenty near-identical toggle options producing hesitation or exit, versus a curated three-option version.",
    diagnosticQuestions: ["Is this friction really about the number of options — or about how poorly differentiated the existing options currently are?"],
    misinterpretations: "The most commonly overapplied principle in this registry. \"Reduce the options\" is not a universal fix — it can remove genuinely useful choice without addressing the real problem.",
    relevantFrictionMechanisms: [{ id: "cognitive_load", primary: true }, { id: "commitment_anxiety", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Do not invoke this to justify reducing options when the actual, better-evidenced problem is Hick's-Law-style poor differentiation between the options that already exist."],
    references: [{ label: "Iyengar & Lepper, 2000" }, { label: "Scheibehenne, Greifeneder & Todd, 2010", note: "meta-analysis showing near-zero average effect" }],
  },

  // ── Family 05 — Anchoring, Reference Points & Framing ─────────────────────
  {
    id: "anchoring", name: "Anchoring", familyId: "anchoring-framing",
    definition: "An initially presented number biases subsequent numerical judgments toward itself, even when explicitly arbitrary.",
    underlyingMechanism: "Numerical estimation adjusts away from a starting value, and that adjustment is systematically insufficient — people under-correct even when warned in advance.",
    evidenceStrength: "strong",
    evidenceNotes: "One of the most extensively replicated findings since Tversky & Kahneman's 1974 demonstrations, across pricing, legal judgment, and estimation tasks.",
    epistemicWarnings: [],
    manifestation: "A crossed-out \"was $X\" price anchors perceived worth to the higher number, even if that price was never actually charged.",
    diagnosticQuestions: ["What is the first number this visitor sees, and is it actually informative about value — or just the first number they happened to encounter?"],
    misinterpretations: "Anchoring on a fabricated reference price is a trust-destroying misuse of a real mechanism — it resolves against the seller the moment a diligent buyer notices.",
    relevantFrictionMechanisms: [{ id: "value_uncertainty", primary: true }, { id: "trust_deficit", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["A fabricated or misleading anchor is deceptive pricing, not a legitimate application — the psychological effect being real does not make a dishonest anchor acceptable."],
    references: [{ label: "Tversky & Kahneman, 1974" }],
  },
  {
    id: "framing-effect", name: "Framing Effect", familyId: "anchoring-framing",
    definition: "Logically equivalent descriptions of the same information produce different decisions depending on gain or loss presentation.",
    underlyingMechanism: "The same objective outcome is evaluated differently depending on whether it's coded as a gain or loss relative to the reference point the framing implies.",
    evidenceStrength: "strong",
    evidenceNotes: "Directly derived from Prospect Theory (Kahneman & Tversky, 1979, 1981), replicated extensively across medical, financial, and consumer decision-making.",
    epistemicWarnings: [],
    manifestation: "\"Save 20% by paying annually\" versus \"pay 25% more by staying monthly\" describe the same price difference, framed differently.",
    diagnosticQuestions: ["Is the current framing describing this trade-off as a gain to get or a loss to avoid — and is that the psychologically accurate representation?"],
    misinterpretations: "Framing a fact differently is not changing the fact — using framing to obscure a genuinely unfavorable term crosses into manipulation.",
    relevantFrictionMechanisms: [{ id: "value_uncertainty", primary: true }, { id: "commitment_anxiety", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Framing changes psychological salience, not underlying fact — it cannot compensate for a term that is genuinely unfavorable regardless of framing."],
    references: [{ label: "Kahneman & Tversky, 1979, 1981" }],
  },
  {
    id: "contrast-effect", name: "Contrast Effect", familyId: "anchoring-framing",
    definition: "The perceived magnitude of a stimulus is judged relative to recently or simultaneously presented stimuli.",
    underlyingMechanism: "Evaluative systems are comparative by default (Weber's Law). The same absolute price can register as large or small depending on what it's compared against.",
    evidenceStrength: "contextual",
    evidenceNotes: "Strong for the underlying psychophysical mechanism. Its application to deliberate pricing-page sequencing is a reasonable extrapolation with less domain-specific isolation than anchoring or framing.",
    epistemicWarnings: [],
    manifestation: "Presenting an enterprise \"custom pricing\" tier before standard tiers makes the standard tiers feel more moderate.",
    diagnosticQuestions: ["What is this price or claim currently being mentally compared against — and does that comparison reflect the value actually being offered?"],
    misinterpretations: "Distinct from anchoring in mechanism, even though the two often co-occur and get conflated. Overused when a contrast is engineered from items not real or relevant to the buyer's decision.",
    relevantFrictionMechanisms: [{ id: "value_uncertainty", primary: true }, { id: "ordering_error", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["A contrast built from irrelevant or unreal comparison points is manipulation, not legitimate application."],
    references: [{ label: "Weber's Law" }],
  },

  // ── Family 06 — Narrative Clarity & Expectation-Reality Alignment ─────────
  {
    id: "expectation-disconfirmation", name: "Expectation (Dis)confirmation", familyId: "narrative-clarity",
    definition: "Satisfaction is driven less by an experience's absolute quality than by how it compares to the expectation held beforehand.",
    underlyingMechanism: "Incoming experience is evaluated against a pre-formed expectation. The gap — confirmation, positive or negative disconfirmation — drives satisfaction more than objective quality alone.",
    evidenceStrength: "strong",
    evidenceNotes: "Foundational and well-replicated since Oliver (1980), extended directly to SaaS post-adoption satisfaction (Bhattacherjee's IS-continuance model, 2001). One of the better-evidenced entries specifically for the SaaS domain.",
    epistemicWarnings: [],
    manifestation: "Marketing overselling ease-of-setup produces more signups but worse activation, because onboarding negatively disconfirms an inflated expectation.",
    diagnosticQuestions: ["What expectation is the marketing and sales copy setting, and does the product experience meet, exceed, or fall short of it?"],
    misinterpretations: "Not an argument for underselling to \"guarantee\" positive disconfirmation — depressed expectations can suppress conversion so much the later satisfaction gain never happens.",
    relevantFrictionMechanisms: [{ id: "value_uncertainty", primary: true }, { id: "trust_deficit", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Concerns post-conversion satisfaction and retention, not conversion itself — its causal lever is pre-conversion expectation-setting, but the effect it explains happens after."],
    references: [{ label: "Oliver, 1980" }, { label: "Bhattacherjee, 2001", note: "IS-continuance model" }],
  },
  {
    id: "peak-end-rule", name: "Peak-End Rule", familyId: "narrative-clarity",
    definition: "Retrospective evaluation of an experience is disproportionately shaped by its most intense moment and its final moment.",
    underlyingMechanism: "Memory constructs a retrospective summary dominated by a few salient points, not a moment-by-moment average — why total duration has little influence on remembered evaluation.",
    evidenceStrength: "contextual",
    evidenceNotes: "Strong for the original domain (Kahneman's colonoscopy studies, 1993/1996 — acute physical experience). More contextual for extended, low-intensity digital experiences, where the research base is thinner.",
    epistemicWarnings: [],
    manifestation: "A trial ending on a confusing cancellation flow leaves a disproportionately negative impression, even if most of the trial was smooth.",
    diagnosticQuestions: ["What is the most intense friction moment in this flow, and what is the very last thing this visitor experiences before the decision point?"],
    misinterpretations: "Should not justify neglecting the middle of an experience — duration neglect describes memory construction, not real-time abandonment risk.",
    relevantFrictionMechanisms: [{ id: "trust_deficit", primary: true }, { id: "commitment_anxiety", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["The middle of an experience still has real, in-the-moment behavioral impact — this mechanism explains retrospective memory, not real-time abandonment risk."],
    references: [{ label: "Kahneman, 1993, 1996" }],
  },
  {
    id: "zeigarnik-effect", name: "Zeigarnik Effect", familyId: "narrative-clarity",
    definition: "Incomplete or interrupted tasks are believed to be better remembered and generate more cognitive tension than completed ones.",
    underlyingMechanism: "As originally proposed, unresolved goals maintain cognitive tension keeping them accessible in memory — the theoretical basis of progress-bar design patterns.",
    evidenceStrength: "weak",
    evidenceNotes: "The most important honesty flag in this registry alongside Choice Overload. The 1927 original is cited as settled science in UX writing, but replication has been inconsistent and modern reviews question whether it's robust outside narrow lab conditions.",
    epistemicWarnings: [
      "Replication record is considerably weaker than the effect's popular reputation — treat any confident appeal to \"the Zeigarnik effect proves progress bars work\" as an overclaim.",
      "If a progress indicator does prove effective in a given case, prefer a better-supported explanation (reduced uncertainty about remaining effort) over this contested mechanism.",
    ],
    manifestation: "A multi-step onboarding progress bar showing \"3 of 5 steps complete,\" commonly justified by appeal to this effect specifically.",
    diagnosticQuestions: ["Is this incompleteness cue giving useful, honest feedback about remaining effort — or is it being justified by a mechanism that may not be doing the work it's credited with?"],
    misinterpretations: "Invoked with far more certainty than the evidence supports in most secondary UX/marketing sources.",
    relevantFrictionMechanisms: [{ id: "commitment_anxiety", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Do not cite this as the explanatory mechanism for why a progress indicator works without first ruling out simpler, better-supported explanations."],
    references: [{ label: "Zeigarnik, 1927" }],
  },

  // ── Family 07 — Motivation, Emotion & Psychological Friction ──────────────
  {
    id: "self-determination-theory", name: "Self-Determination Theory", familyId: "motivation-emotion",
    definition: "Sustained motivation depends on satisfying three needs — autonomy, competence, relatedness — and degrades when any is thwarted.",
    underlyingMechanism: "Distinguishes intrinsic from extrinsic motivation; external controls can undermine intrinsic motivation even while nominally incentivizing the target behavior (motivation crowding-out).",
    evidenceStrength: "strong",
    evidenceNotes: "One of the most extensively validated theories in motivational psychology since Deci & Ryan's 1970s work, with direct application to software onboarding and habit formation.",
    epistemicWarnings: [],
    manifestation: "A forced, linear onboarding wizard that doesn't let a new user skip to what they actually want reduces perceived autonomy and can lower activation.",
    diagnosticQuestions: ["Does the visitor feel like they're choosing to proceed or being made to proceed — and does the flow give evidence of their own growing competence?"],
    misinterpretations: "Not an argument for unstructured freedom — pure autonomy without scaffolding can undermine the competence need. The theory calls for balancing all three needs.",
    relevantFrictionMechanisms: [{ id: "identity_friction", primary: true }, { id: "commitment_anxiety", primary: true }],
    relevantPerformanceSignals: [],
    contraindications: ["Concerns sustained, especially intrinsic, motivation — less predictive for one-off, purely transactional decisions with no ongoing engagement component."],
    references: [{ label: "Deci & Ryan" }],
  },
  {
    id: "commitment-consistency", name: "Commitment & Consistency", familyId: "motivation-emotion",
    definition: "Once people make a small commitment, they feel internal pressure to behave consistently with it on later, larger requests.",
    underlyingMechanism: "Consistency functions as a heuristic for a coherent self-concept; violating it carries a psychological cost. Strongest when the initial commitment was active, effortful, and freely chosen.",
    evidenceStrength: "strong",
    evidenceNotes: "Grounded in Cialdini (1984) and foot-in-the-door research (Freedman & Fraser, 1966), substantially replicated — though effect size depends heavily on how voluntary and effortful the first step was.",
    epistemicWarnings: [],
    manifestation: "A visitor who completes a short, specific diagnostic quiz about their own funnel is more likely to purchase a paid diagnostic than one shown the same offer cold.",
    diagnosticQuestions: ["What small commitment has this visitor already made, and does the next ask align with or contradict what that commitment implies about them?"],
    misinterpretations: "Manufacturing trivial \"commitments\" — a meaningless click framed as agreement — exploits the name without the actual precondition of genuine effort, and tends to produce little real pull.",
    relevantFrictionMechanisms: [{ id: "commitment_anxiety", primary: true }, { id: "identity_friction", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Works forward from a genuine, voluntary, effortful first step — not reliable as a one-shot device without a real prior commitment already in place."],
    references: [{ label: "Cialdini, 1984" }, { label: "Freedman & Fraser, 1966" }],
  },
  {
    id: "negativity-bias", name: "Negativity Bias in Risk Evaluation", familyId: "motivation-emotion",
    definition: "Negative information and potential negative outcomes are weighted more heavily than positive information of equivalent magnitude.",
    underlyingMechanism: "Threat-relevant information receives prioritized processing over reward-relevant information, plausibly reflecting an evolved asymmetry between missing a threat and missing an opportunity.",
    evidenceStrength: "strong",
    evidenceNotes: "Strong for the general phenomenon (Baumeister et al.'s \"bad is stronger than good\" review, 2001). Contextual for its exact weighting at any single SaaS decision point.",
    epistemicWarnings: [],
    manifestation: "A single visible negative review exerts more influence on a prospect's evaluation than several positive reviews of equal specificity.",
    diagnosticQuestions: ["What is the most salient negative signal a prospect could encounter, and is anything addressing or contextualizing it?"],
    misinterpretations: "Not a justification for suppressing negative information — honest handling of a known negative can itself function as a trust signal.",
    relevantFrictionMechanisms: [{ id: "trust_deficit", primary: true }, { id: "commitment_anxiety", primary: false }],
    relevantPerformanceSignals: [],
    contraindications: ["Does not by itself mean negative framing motivates action better than positive framing in every context — that is a separate claim (see Framing Effect) requiring its own evidence."],
    references: [{ label: "Baumeister et al., 2001" }],
  },
];
