"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getAuthHeaders } from "@/lib/supabase";
import { ADMIN_MODULES, ADMIN_MODULE_BY_ID, type AdminModuleId } from "@/lib/admin-module-registry";

type Signal={health:"ready"|"attention"|"unavailable";value:number|null;label:string;detail:string;error?:string};
type Payload={observedAt:string;date:string;modules:Partial<Record<AdminModuleId,Signal>>};
function day(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}

export default function Overview(){
 const [live,setLive]=useState<Payload|null>(null),[error,setError]=useState<string|null>(null);
 const date=useMemo(day,[]);
 useEffect(()=>{void fetch(`/api/system/overview?date=${date}`,{headers:getAuthHeaders()}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||`System overview ${r.status}`);setLive(j)}).catch(e=>setError(e instanceof Error?e.message:"Live system state unavailable"))},[date]);
 const liveConnections=ADMIN_MODULES.flatMap(m=>m.connections.filter(c=>c.status==="live").map(c=>`${m.label} → ${labelFor(c.target)}`));
 const plannedConnections=ADMIN_MODULES.reduce((n,m)=>n+m.connections.filter(c=>c.status==="planned").length,0);
 return <main className="min-h-screen p-5 md:p-8 text-[#F5F0EB]"><div className="max-w-[1500px] mx-auto space-y-6">
  <header className="border-b border-[#D4A853]/15 pb-6 flex flex-col xl:flex-row xl:items-end justify-between gap-5"><div><span className="font-mono text-[10px] uppercase tracking-[.35em] text-[#D4A853]/70">Backend Operating System · Canonical Projection</span><h1 className="font-serif text-4xl mt-1">Know what exists, what it owns, and what it feeds.</h1><p className="text-sm text-[#8D837A] mt-2 max-w-4xl leading-relaxed">A module is alive only when its purpose, source of truth, operating state and cross-module contracts are explicit. <span className="text-[#5C9A6B]">LIVE</span> means the connection exists in code/data today. <span className="text-amber-400">PLANNED</span> is an admitted gap, not a UI promise.</p></div><div className="grid grid-cols-3 gap-2 min-w-[360px]"><K l="Modules" v={ADMIN_MODULES.length}/><K l="Live links" v={liveConnections.length}/><K l="Planned gaps" v={plannedConnections}/></div></header>
  {error&&<div className="border border-[#C85C5C]/30 bg-[#C85C5C]/8 rounded-lg px-4 py-3 text-xs font-mono text-[#C85C5C]">Runtime health projection unavailable: {error}. Architecture contracts remain visible; live counts do not.</div>}
  <section className="grid lg:grid-cols-2 2xl:grid-cols-3 gap-4">{ADMIN_MODULES.map(m=><ModuleCard key={m.id} id={m.id} signal={live?.modules[m.id]}/>)}</section>
  <section className="border border-[#D4A853]/12 rounded-xl bg-[#110F0D]/55 overflow-hidden"><div className="p-5 border-b border-[#D4A853]/10 flex flex-wrap justify-between gap-3"><div><span className="font-mono text-[10px] uppercase tracking-[.2em] text-[#D4A853]">Living system graph</span><h2 className="font-serif text-xl mt-1">Connections that actually exist</h2></div><span className="text-[10px] font-mono text-[#7A6F65]">observed {live?.observedAt?new Date(live.observedAt).toLocaleTimeString():"—"}</span></div><div className="p-5 grid md:grid-cols-2 xl:grid-cols-3 gap-2">{ADMIN_MODULES.flatMap(m=>m.connections.filter(c=>c.status==="live").map((c,i)=><div key={`${m.id}-${i}`} className="border border-[#5C9A6B]/15 rounded-lg p-3 bg-[#5C9A6B]/[0.03]"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.12em]"><span className="text-[#F5F0EB]">{m.label}</span><span className="text-[#5C9A6B]">→</span><span className="text-[#F5F0EB]">{labelFor(c.target)}</span><span className="ml-auto text-[#5C9A6B]">LIVE</span></div><p className="text-[11px] text-[#8D837A] mt-2 leading-relaxed">{c.contract}</p></div>))}</div></section>
 </div></main>
}

function ModuleCard({id,signal}:{id:AdminModuleId;signal?:Signal}){const m=ADMIN_MODULE_BY_ID[id];return <article className="border border-[#D4A853]/12 rounded-xl bg-[#110F0D]/60 overflow-hidden flex flex-col"><div className="p-5 border-b border-[#D4A853]/8"><div className="flex items-start justify-between gap-3"><div><span className="font-mono text-[10px] text-[#D4A853] tracking-[.18em]">{m.code}</span><h2 className="font-serif text-2xl mt-0.5">{m.label}</h2></div><Health s={signal}/></div><p className="text-sm text-[#B0A89E] mt-3 leading-relaxed">{m.purpose}</p></div><div className="p-5 space-y-4 flex-1"><Row k="Source of truth" v={m.sourceOfTruth}/><Row k="Owns" v={m.owns}/><div className="grid grid-cols-2 gap-3"><Mini k="Receives" values={m.receives}/><Mini k="Produces" values={m.produces}/></div><div><span className="font-mono text-[9px] uppercase tracking-[.15em] text-[#7A6F65]">Connections</span><div className="mt-2 space-y-1.5">{m.connections.map((c,i)=><div key={i} className="flex gap-2 items-start"><span className={`mt-0.5 font-mono text-[9px] min-w-[50px] ${c.status==="live"?"text-[#5C9A6B]":"text-amber-400"}`}>{c.status.toUpperCase()}</span><span className="text-[11px] text-[#8D837A] leading-relaxed"><span className="text-[#D4A853]">{labelFor(c.target)}</span> · {c.contract}</span></div>)}</div></div></div><div className="p-4 border-t border-[#D4A853]/8 flex flex-wrap gap-2">{m.surfaces.map(s=><Link key={s.href} href={s.href} className="border border-[#D4A853]/18 hover:border-[#D4A853]/40 rounded px-3 py-1.5 text-[10px] font-mono uppercase tracking-[.12em] text-[#D4A853]">Open {s.label}</Link>)}</div></article>}
function Health({s}:{s?:Signal}){if(!s)return <span className="border border-[#7A6F65]/20 rounded px-2 py-1 text-[9px] font-mono uppercase text-[#7A6F65]">Checking…</span>;const c=s.health==="ready"?"text-[#5C9A6B] border-[#5C9A6B]/25":s.health==="attention"?"text-amber-400 border-amber-400/25":"text-[#C85C5C] border-[#C85C5C]/25";return <div className={`border rounded px-2.5 py-1.5 text-right ${c}`}><span className="block text-[9px] font-mono uppercase">{s.health}</span><span className="block text-sm font-mono tabular-nums">{s.value??"—"} <span className="text-[9px]">{s.label}</span></span></div>}
function Row({k,v}:{k:string;v:string}){return <div><span className="font-mono text-[9px] uppercase tracking-[.15em] text-[#7A6F65]">{k}</span><p className="text-[11px] text-[#A79D93] leading-relaxed mt-1">{v}</p></div>}
function Mini({k,values}:{k:string;values:string[]}){return <div className="border border-[#D4A853]/8 rounded-lg p-3"><span className="font-mono text-[9px] uppercase tracking-[.15em] text-[#7A6F65]">{k}</span>{values.map(v=><span key={v} className="block text-[10px] text-[#A79D93] mt-1.5 leading-relaxed">· {v}</span>)}</div>}
function K({l,v}:{l:string;v:number}){return <div className="border border-[#D4A853]/10 rounded-lg p-3 bg-[#110F0D]"><span className="block text-[9px] font-mono uppercase tracking-[.15em] text-[#7A6F65]">{l}</span><span className="block font-serif text-xl mt-1">{v}</span></div>}
function labelFor(target:string){if(target in ADMIN_MODULE_BY_ID)return ADMIN_MODULE_BY_ID[target as AdminModuleId].label;if(target==="premium_authorization")return"Premium Authorization";return"Operator"}
