import { createClient } from '@supabase/supabase-js';
import { requireAdmin } from '../_admin-auth';
import { getSupabaseUrl, getServiceRoleKey } from '../_env';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Content-Type': 'application/json',
};

// The 7 judgment fields, the 3 companion classifiers, and loom_script are
// the only writable fields here — evidence, technical_signals, target_url,
// domain, scanned_at, client_id, prospect_candidate_id, and
// loom_script_generated_at are set once at generation and are immutable
// here. Regenerate to refresh measured data; never hand-edit it.
// loom_script itself IS meant to be hand-revised after generation — that's
// the point of exposing it here — but it's never generated by this
// endpoint, only by scaffolds/generate-loom.ts.
//
// funnel_stage / projected_impact_magnitude / confidence_level power
// generateTeaser() and applyDosing()'s "region"/"partial_label" disclosure
// levels (src/lib/dosing.ts) — until these were added here, there was no
// way to set them outside direct SQL, so every UI-created scaffold left
// them null forever and the teaser/dosed-preview degraded to generic
// fallback phrasing with no error to explain why.
const EDITABLE_FIELDS = [
  'friction_mechanism',
  'specific_friction_point',
  'why_blocks_conversion',
  'projected_impact',
  'the_decision',
  'what_to_avoid',
  'confidence_and_why',
  'loom_script',
  'funnel_stage',
  'projected_impact_magnitude',
  'confidence_level',
  'unknowns',
] as const;

type EditableField = (typeof EDITABLE_FIELDS)[number];

// reasoning_links is validated separately from EDITABLE_FIELDS above
// because it's a JSONB array, not a string like every other field — the
// generic string-typed loop below can't handle it. Phase 3 constraint,
// enforced server-side (not just in the admin UI, which is trivially
// bypassable): every attached mechanism MUST carry a real, non-empty
// analyst-authored rationale. A suggested mechanism with no rationale is
// rejected outright — this is the boundary that makes "a suggestion
// never counts as evidence" actually true rather than a UI convention.
interface ReasoningLinkInput {
  id: unknown;
  mechanismId: unknown;
  frictionMechanism: unknown;
  status: unknown;
  evidenceStrength: unknown;
  analystRationale: unknown;
  linkedObservationIds: unknown;
}

function validateReasoningLinks(value: unknown): { ok: true; links: ReasoningLinkInput[] } | { ok: false; error: string } {
  if (!Array.isArray(value)) {
    return { ok: false, error: 'reasoning_links must be an array' };
  }
  for (const [i, raw] of value.entries()) {
    const link = raw as Partial<ReasoningLinkInput>;
    if (typeof link.mechanismId !== 'string' || !link.mechanismId) {
      return { ok: false, error: `reasoning_links[${i}]: mechanismId is required` };
    }
    if (typeof link.analystRationale !== 'string' || link.analystRationale.trim().length === 0) {
      return { ok: false, error: `reasoning_links[${i}]: analystRationale is required — an attached mechanism with no stated reason is not allowed. A suggestion is not evidence until an analyst explains why it applies here.` };
    }
    if (link.status !== 'modeled' && link.status !== 'pending') {
      return { ok: false, error: `reasoning_links[${i}]: status must be "modeled" or "pending" — never "measured", a hypothesis is not itself a measurement` };
    }
  }
  return { ok: true, links: value as ReasoningLinkInput[] };
}

export const onRequestPatch = async ({
  params,
  request,
  env,
}: {
  params: { id: string };
  request: Request;
  env: Record<string, string>;
}): Promise<Response> => {
  const admin = await requireAdmin(request, env);
  if (admin instanceof Response) {
    const body = await admin.json().catch(() => ({}));
    return Response.json(body, { status: admin.status, headers: CORS });
  }

  const { id } = params;

  let payload: Record<string, unknown>;
  try {
    payload = await request.json();
  } catch {
    return Response.json({ error: 'Invalid request body' }, { status: 400, headers: CORS });
  }

  const allKeys: string[] = [...EDITABLE_FIELDS, 'reasoning_links'];
  const disallowedKeys = Object.keys(payload).filter((k) => !allKeys.includes(k));
  if (disallowedKeys.length > 0) {
    return Response.json(
      { error: `Not editable via this endpoint: ${disallowedKeys.join(', ')}.` },
      { status: 400, headers: CORS }
    );
  }

  const update: Record<string, unknown> = { updated_at: new Date().toISOString() };
  for (const field of EDITABLE_FIELDS) {
    if (payload[field] !== undefined) {
      if (typeof payload[field] !== 'string') {
        return Response.json({ error: `${field} must be a string` }, { status: 400, headers: CORS });
      }
      update[field] = payload[field];
    }
  }

  if (payload.reasoning_links !== undefined) {
    const result = validateReasoningLinks(payload.reasoning_links);
    if (!result.ok) {
      return Response.json({ error: result.error }, { status: 400, headers: CORS });
    }
    update.reasoning_links = result.links;
  }

  if (Object.keys(update).length === 1) {
    // Only updated_at present — nothing real to save.
    return Response.json({ error: 'No fields to update' }, { status: 400, headers: CORS });
  }

  const supabaseUrl = getSupabaseUrl(env);
  const serviceRoleKey = getServiceRoleKey(env);
  if (!serviceRoleKey) {
    return Response.json({ error: 'Server misconfiguration: SUPABASE_SERVICE_ROLE_KEY not set' }, { status: 500, headers: CORS });
  }
  const supabase = createClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: updated, error } = await supabase
    .from('diagnostic_scaffolds')
    .update(update)
    .eq('id', id)
    .select()
    .single();

  if (error || !updated) {
    return Response.json({ error: error?.message ?? 'Scaffold not found' }, { status: 404, headers: CORS });
  }

  return Response.json(updated, { headers: CORS });
};

export const onRequestOptions = (): Response =>
  new Response(null, {
    status: 204,
    headers: {
      ...CORS,
      'Access-Control-Allow-Methods': 'PATCH, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    },
  });
